import mongoose from "mongoose";
import "dotenv/config";
const uri = process.env.MONGODB_URI;
await mongoose.connect(uri);
const db = mongoose.connection;
const depositCount = await db.collection("cryptodepositrequests").countDocuments({});
console.log("Leftover CryptoDepositRequest docs:", depositCount);
const assets = await db.collection("cryptoassets").find({}).toArray();
console.log("Current CryptoAsset docs:");
assets.forEach(a => console.log(` - ${a.symbol} coingeckoId=${a.coingeckoId || "MISSING"}`));
await mongoose.disconnect();
